"use strict";
Object.defineProperty(exports, "__esModule", { value: true });
exports.Timelock__factory = void 0;
/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
var Timelock__factory_1 = require("./Timelock__factory");
Object.defineProperty(exports, "Timelock__factory", { enumerable: true, get: function () { return Timelock__factory_1.Timelock__factory; } });
