"use strict";
Object.defineProperty(exports, "__esModule", { value: true });
exports.DoubleEndedQueue__factory = void 0;
/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
var DoubleEndedQueue__factory_1 = require("./DoubleEndedQueue__factory");
Object.defineProperty(exports, "DoubleEndedQueue__factory", { enumerable: true, get: function () { return DoubleEndedQueue__factory_1.DoubleEndedQueue__factory; } });
