/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
export * as erc20 from "./ERC20";
export * as lockSol from "./Lock.sol";
export * as governance from "./governance";
export * as interfaces from "./interfaces";
export * as security from "./security";
export * as utils from "./utils";
export { Governor_Token__factory } from "./Governor_Token__factory";
export { Ink_Governor__factory } from "./Ink_Governor__factory";
export { Timelock_Governor__factory } from "./Timelock_Governor__factory";
