"use strict";
var __createBinding = (this && this.__createBinding) || (Object.create ? (function(o, m, k, k2) {
    if (k2 === undefined) k2 = k;
    var desc = Object.getOwnPropertyDescriptor(m, k);
    if (!desc || ("get" in desc ? !m.__esModule : desc.writable || desc.configurable)) {
      desc = { enumerable: true, get: function() { return m[k]; } };
    }
    Object.defineProperty(o, k2, desc);
}) : (function(o, m, k, k2) {
    if (k2 === undefined) k2 = k;
    o[k2] = m[k];
}));
var __setModuleDefault = (this && this.__setModuleDefault) || (Object.create ? (function(o, v) {
    Object.defineProperty(o, "default", { enumerable: true, value: v });
}) : function(o, v) {
    o["default"] = v;
});
var __importStar = (this && this.__importStar) || function (mod) {
    if (mod && mod.__esModule) return mod;
    var result = {};
    if (mod != null) for (var k in mod) if (k !== "default" && Object.prototype.hasOwnProperty.call(mod, k)) __createBinding(result, mod, k);
    __setModuleDefault(result, mod);
    return result;
};
Object.defineProperty(exports, "__esModule", { value: true });
exports.Timelock_Governor__factory = exports.Ink_Governor__factory = exports.Governor_Token__factory = exports.utils = exports.security = exports.interfaces = exports.governance = exports.lockSol = exports.erc20 = void 0;
/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
exports.erc20 = __importStar(require("./ERC20"));
exports.lockSol = __importStar(require("./Lock.sol"));
exports.governance = __importStar(require("./governance"));
exports.interfaces = __importStar(require("./interfaces"));
exports.security = __importStar(require("./security"));
exports.utils = __importStar(require("./utils"));
var Governor_Token__factory_1 = require("./Governor_Token__factory");
Object.defineProperty(exports, "Governor_Token__factory", { enumerable: true, get: function () { return Governor_Token__factory_1.Governor_Token__factory; } });
var Ink_Governor__factory_1 = require("./Ink_Governor__factory");
Object.defineProperty(exports, "Ink_Governor__factory", { enumerable: true, get: function () { return Ink_Governor__factory_1.Ink_Governor__factory; } });
var Timelock_Governor__factory_1 = require("./Timelock_Governor__factory");
Object.defineProperty(exports, "Timelock_Governor__factory", { enumerable: true, get: function () { return Timelock_Governor__factory_1.Timelock_Governor__factory; } });
