/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type * as implementationSol from "./Implementation.sol";
export type { implementationSol };
export type { ECDSA_Recover } from "./ECDSA_Recover";
