"use strict";
Object.defineProperty(exports, "__esModule", { value: true });
exports.IGovernorTimelock__factory = exports.GovernorVotesQuorumFraction__factory = exports.GovernorVotes__factory = exports.GovernorTimelockControl__factory = exports.GovernorSettings__factory = exports.GovernorCountingSimple__factory = void 0;
/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
var GovernorCountingSimple__factory_1 = require("./GovernorCountingSimple__factory");
Object.defineProperty(exports, "GovernorCountingSimple__factory", { enumerable: true, get: function () { return GovernorCountingSimple__factory_1.GovernorCountingSimple__factory; } });
var GovernorSettings__factory_1 = require("./GovernorSettings__factory");
Object.defineProperty(exports, "GovernorSettings__factory", { enumerable: true, get: function () { return GovernorSettings__factory_1.GovernorSettings__factory; } });
var GovernorTimelockControl__factory_1 = require("./GovernorTimelockControl__factory");
Object.defineProperty(exports, "GovernorTimelockControl__factory", { enumerable: true, get: function () { return GovernorTimelockControl__factory_1.GovernorTimelockControl__factory; } });
var GovernorVotes__factory_1 = require("./GovernorVotes__factory");
Object.defineProperty(exports, "GovernorVotes__factory", { enumerable: true, get: function () { return GovernorVotes__factory_1.GovernorVotes__factory; } });
var GovernorVotesQuorumFraction__factory_1 = require("./GovernorVotesQuorumFraction__factory");
Object.defineProperty(exports, "GovernorVotesQuorumFraction__factory", { enumerable: true, get: function () { return GovernorVotesQuorumFraction__factory_1.GovernorVotesQuorumFraction__factory; } });
var IGovernorTimelock__factory_1 = require("./IGovernorTimelock__factory");
Object.defineProperty(exports, "IGovernorTimelock__factory", { enumerable: true, get: function () { return IGovernorTimelock__factory_1.IGovernorTimelock__factory; } });
