"use strict";
Object.defineProperty(exports, "__esModule", { value: true });
exports.CallReceiverMock__factory = void 0;
/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
const ethers_1 = require("ethers");
const _abi = [
    {
        anonymous: false,
        inputs: [],
        name: "MockFunctionCalled",
        type: "event",
    },
    {
        anonymous: false,
        inputs: [
            {
                indexed: false,
                internalType: "uint256",
                name: "a",
                type: "uint256",
            },
            {
                indexed: false,
                internalType: "uint256",
                name: "b",
                type: "uint256",
            },
        ],
        name: "MockFunctionCalledWithArgs",
        type: "event",
    },
    {
        inputs: [],
        name: "mockFunction",
        outputs: [
            {
                internalType: "string",
                name: "",
                type: "string",
            },
        ],
        stateMutability: "payable",
        type: "function",
    },
    {
        inputs: [],
        name: "mockFunctionOutOfGas",
        outputs: [],
        stateMutability: "payable",
        type: "function",
    },
    {
        inputs: [],
        name: "mockFunctionRevertsNoReason",
        outputs: [
            {
                internalType: "string",
                name: "",
                type: "string",
            },
        ],
        stateMutability: "pure",
        type: "function",
    },
    {
        inputs: [],
        name: "mockFunctionRevertsReason",
        outputs: [],
        stateMutability: "payable",
        type: "function",
    },
    {
        inputs: [],
        name: "mockFunctionThrows",
        outputs: [],
        stateMutability: "payable",
        type: "function",
    },
];
const _bytecode = "0x608060405234801561001057600080fd5b50610245806100206000396000f3fe60806040526004361061004a5760003560e01c80630c0349681461004f5780632c81d638146100595780633bcfaa14146100845780633e6fec041461008c578063a793ab4714610094575b600080fd5b61005761009c565b005b34801561006557600080fd5b5061006e600080fd5b60405161007b9190610184565b60405180910390f35b6100576100e8565b61006e6100f2565b61005761013f565b60405162461bcd60e51b815260206004820152601b60248201527f43616c6c52656365697665724d6f636b3a20726576657274696e670000000000604482015260640160405180910390fd5b6100f06101d2565b565b6040516060907f52c66ed6ec9ca819cba26fe2b2650059270d8981b295af300187a964f54a8c2390600090a1506040805180820190915260068152650c1e0c4c8ccd60d21b602082015290565b60005b600080546001810182559080527f290decd9548b62a8d60345a988386fc84ba6bc95484008f6362f93160ef3e5630181905561017d816101e8565b9050610142565b600060208083528351808285015260005b818110156101b157858101830151858201604001528201610195565b506000604082860101526040601f19601f8301168501019250505092915050565b634e487b7160e01b600052600160045260246000fd5b60006001820161020857634e487b7160e01b600052601160045260246000fd5b506001019056fea26469706673582212208afc24a0666a1450812365c87973a8c9abc2aa9ecf7b8ec341c5f83d29c6470a64736f6c63430008110033";
const isSuperArgs = (xs) => xs.length > 1;
class CallReceiverMock__factory extends ethers_1.ContractFactory {
    constructor(...args) {
        if (isSuperArgs(args)) {
            super(...args);
        }
        else {
            super(_abi, _bytecode, args[0]);
        }
    }
    deploy(overrides) {
        return super.deploy(overrides || {});
    }
    getDeployTransaction(overrides) {
        return super.getDeployTransaction(overrides || {});
    }
    attach(address) {
        return super.attach(address);
    }
    connect(signer) {
        return super.connect(signer);
    }
    static createInterface() {
        return new ethers_1.utils.Interface(_abi);
    }
    static connect(address, signerOrProvider) {
        return new ethers_1.Contract(address, _abi, signerOrProvider);
    }
}
exports.CallReceiverMock__factory = CallReceiverMock__factory;
CallReceiverMock__factory.bytecode = _bytecode;
CallReceiverMock__factory.abi = _abi;
