"use strict";
Object.defineProperty(exports, "__esModule", { value: true });
exports.Implementation2__factory = exports.CallReceiverMock__factory = void 0;
/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
var CallReceiverMock__factory_1 = require("./CallReceiverMock__factory");
Object.defineProperty(exports, "CallReceiverMock__factory", { enumerable: true, get: function () { return CallReceiverMock__factory_1.CallReceiverMock__factory; } });
var Implementation2__factory_1 = require("./Implementation2__factory");
Object.defineProperty(exports, "Implementation2__factory", { enumerable: true, get: function () { return Implementation2__factory_1.Implementation2__factory; } });
